# Generated by Django 3.0.7 on 2020-06-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200606_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
