# Generated by Django 3.0.7 on 2020-06-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200606_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hasExtra',
            field=models.BooleanField(default=False),
        ),
    ]
