# Generated by Django 3.0.7 on 2020-06-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200607_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
