# Generated by Django 3.0.7 on 2020-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200607_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='size',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
