# Generated by Django 3.0.7 on 2020-06-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200607_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
