# Generated by Django 3.0.7 on 2020-06-07 17:08

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200607_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='open', max_length=50),
            preserve_default=False,
        ),
    ]
