# Generated by Django 3.0.7 on 2020-06-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200613_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Customer',
        ),
    ]
