# Generated by Django 3.0.7 on 2020-06-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200613_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address3',
        ),
    ]
