# Generated by Django 3.0.7 on 2020-06-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200614_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunityproduct',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='opportunityproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
        migrations.DeleteModel(
            name='OpportunityProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
